import Head from 'next/head'
import Nav from './components/Navigation'
import Link from 'next/link'
import Image from 'next/dist/client/image'


export default function Home({ data }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <Nav />


      {data.articles.map((res) => {
        let image = res.media;
        return (
          <>
            <div className='relative'>

              <div className=" w-[90%] sm:w-1/2 mx-auto mt-8 shadow-lg p-4 sm:p-10  rounded-xl shadow-blue-200 ">
                <Link href={res.link}><a >

                  <Image className='object-cover' key={res.id} src={image} alt={res.title} width={500} height={400} layout='responsive' />
                  <h1 key={res.id} className='text-xl mt-2'>{res.title}</h1>
                </a></Link>
              </div>
            </div>
          </>
        )
      })}


    </div>
  )
}

export async function getStaticProps() {
  const res = await fetch("https://free-news.p.rapidapi.com/v1/search?q=Elon%20Musk&lang=en", {
    "method": "GET",
    "headers": {
      "x-rapidapi-host": "free-news.p.rapidapi.com",
      "x-rapidapi-key": "eb24db375bmsh013c41221c7942fp1de130jsnf98eaf396ddf"
    }
  });
  const data = await res.json();

  return {
    props: {
      data,
    }
  }
}
